---
  r1:
    hostname: 11.0.0.2
    port: 22
    username: cisco
    password: cisco
    platform: ios
    groups: 
        - 'India'
    data:
      loopback: 1.1.1.1
      
  r2:
    hostname: 11.0.0.3
    port: 22
    username: cisco
    password: cisco
    platform: ios
    groups: 
        - 'USA'
    data:
      loopback: 2.2.2.2

