---
  r1:
    hostname: 11.0.0.2
    port: 22
    username: cisco
    password: cisco
    platform: ios

  r2:
    hostname: 11.0.0.3
    port: 22
    username: cisco
    password: cisco
    platform: ios
